from nginx:1.13-alpine
run mkdir -p /var/wwwroot && mkdir -p /etc/nginx/conf.d/ssl
add weiphp.cluby.cn.conf /etc/nginx/conf.d
add test.cluby.cn.conf /etc/nginx/conf.d
add index.html /usr/share/nginx/html/index.html
user root
